version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=pipauls
      - POSTGRES_PASSWORD=pipauls
      - POSTGRES_MULTIPLE_DATABASES=djangotuto-test
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - 5431:5432
  pipauls:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  data:
    driver: local
  pgdata:
